### ISSUE TITLE
SwipeGesture.direction  related to the size of the sketch???

### ISSUE THREAD

**Issue by Javingka** [nok/leap-motion-processing#3]
I'm getting the direction from a SwipeGesture with a PVector, but to get numbers near to 0 (that change its value from negative to positive when I move my hand from one side to other), I have to substract a PVector with;
x = width/2;
y = height;
z = 50;

Does this sound familiar to you?.  I can't figure out why this is happening. 

Thanks.

**Comment by nok** [comment]
Hello @Javingka,

you are right. For this purpose there is the method `getRawDirection()`, which returns the unrelated directions. Nevertheless today I'm going to push an update, where [getRawDirection](https://github.com/nok/leap-motion-processing/blob/master/src/de/voidplus/leapmotion/SwipeGesture.java#L76) will replace [getDirection](https://github.com/nok/leap-motion-processing/blob/master/src/de/voidplus/leapmotion/SwipeGesture.java#L67), because it doesn't make sense, so I agree with you. The method `getRawDirection()` will be deleted for all related gesture types (`SwipeGesture`, `KeyTapGesture`, `ScreenTapGesture`) as well as for the `Hand` class.

Thank you and happy coding,
Darius

**Comment by nok** [comment]
Hello @Javingka,

you're right. I fixed that behaviour for all related gesture types with the last update.

Thank you and happy coding,
Darius
