### ISSUE TITLE
Roll pitch pb with latest release

### ISSUE THREAD

**Issue by Adiou** [nok/leap-motion-processing#7]
Hi, 
Thanks for your very good work with this librairie.

Before the latest release, pitch datas and roll datas was reverse, but there where clean and robust. You obviously wanted to fix this name pb in the latest release (v2.3.1.3), but I think you made a litlle mistake or forgot something somewhere, because datas are now really bad, like if they mix themself together and are very erratic, so we can't use them anymore : move on the x axis change pitch AND roll data, open the hand change data, etc...

Do you have the same pb at home? I delete the newest version of the lib (v2.3.1.3) and replace it by the one just before (v2.3.1.2), and no pb (just have to change roll and pitch name).

Best regards, 

Adrien

**Comment by nok** [comment]
Hello Adrien, do you use the [getRoll()](https://github.com/nok/leap-motion-processing/blob/f2d4596b75ed8450ecb60d16bc57de21a8b0c29d/src/de/voidplus/leapmotion/Hand.java#L275) and [getPitch()](https://github.com/nok/leap-motion-processing/blob/f2d4596b75ed8450ecb60d16bc57de21a8b0c29d/src/de/voidplus/leapmotion/Hand.java#L284) methods directly?

I double checked my past commit: https://github.com/nok/leap-motion-processing/commit/4c732629a87552ac27edf64eb66aa318f77bc149. And you are right, there I forgot to apply the right method. But it's curious, because I tested it with my LM controller. Nevertheless, I will check it again.

In addition you can find older releases in the [release](https://github.com/nok/leap-motion-processing/releases) section.

Darius

**Comment by nok** [comment]
So it's fixed. I tested it with a translated `box()`:

![tested](https://cloud.githubusercontent.com/assets/670641/16569798/0623a850-423b-11e6-863b-4273064eb784.png)

```java
if (leap.hasHands()) {
	ArrayList<Hand> hands = leap.getHands();
	for (Hand hand : leap.getHands()) {
		fill(61,129,247, 100);
		PVector position = hand.getPalmPosition();
		PVector orientation = hand.getDynamics();
		pushMatrix();
		translate(position.x, position.y, position.z);
		rotateX(PApplet.radians(orientation.y));
		rotateY(PApplet.radians(orientation.z));
		rotateZ(PApplet.radians(orientation.x));
		box(60, 5, 120);
		popMatrix();
		hand.draw();
	}
}
```

That's the related commit of the fix: https://github.com/nok/leap-motion-processing/commit/038c245a5c544d63bd516beaa7ad64d5412564ce

Either you wait until the next update `2.3.1.4 (22)` (~1 day) or you [download](https://github.com/nok/leap-motion-processing/blob/master/download/LeapMotionForProcessing.zip?raw=true) the library from this repository.

Again, sorry and thanks @Adiou for the note.
